#!/usr/bin/env bash
cat <<'EOL'
## delete local branch
git branch -d branch_name

## force delete local branch
git branch -D branch_name

## delete remote branch
git push origin --delete branch_name

## further reading:
#  ~/.src/github/asmrtfm/mdocs/git/git_delete_branch*.md
EOL
